### ISSUE TITLE
UnsupportedOperationException opening User sessions

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-audit#11]
- create project
- add audit addon
- add menu item for user sessions:
```
<item screen="userSessions.browse" caption="msg://io.jmix.auditui.screen.sessions/UserSessions.browse"/>
```

- launch app
- open User sessions in menu

Exception:
![image](https://user-images.githubusercontent.com/6158807/95595790-a2882600-0a5d-11eb-98fa-b43f049d789d.png)

<details>
 <summary>Click to expand</summary>
 
```java
...
Caused by: java.lang.UnsupportedOperationException: null
	at io.jmix.core.Entity.__getEntityEntry(Entity.java:27) ~[jmix-core-0.1.0-SNAPSHOT.jar:na]
	at io.jmix.core.entity.EntitySystemAccess.getEntityEntry(EntitySystemAccess.java:33) ~[jmix-core-0.1.0-SNAPSHOT.jar:na]
	at io.jmix.core.entity.EntitySystemAccess.addPropertyChangeListener(EntitySystemAccess.java:102) ~[jmix-core-0.1.0-SNAPSHOT.jar:na]
	at io.jmix.ui.model.impl.InstanceContainerImpl.attachListener(InstanceContainerImpl.java:131) ~[jmix-ui-0.1.0-SNAPSHOT.jar:na]
	at io.jmix.ui.model.impl.CollectionContainerImpl.attachListener(CollectionContainerImpl.java:246) ~[jmix-ui-0.1.0-SNAPSHOT.jar:na]
	at io.jmix.ui.model.impl.CollectionContainerImpl.setItems(CollectionContainerImpl.java:102) ~[jmix-ui-0.1.0-SNAPSHOT.jar:na]
	at io.jmix.ui.model.impl.CollectionLoaderImpl.load(CollectionLoaderImpl.java:100) ~[jmix-ui-0.1.0-SNAPSHOT.jar:na]
	at io.jmix.auditui.screen.sessions.UserSessionsBrowse.onInit(UserSessionsBrowse.java:60) ~[jmix-audit-ui-0.1.0-SNAPSHOT.jar:na]
	at io.jmix.core.common.event.EventHub.publish(EventHub.java:170) ~[jmix-core-0.1.0-SNAPSHOT.jar:na]
	at io.jmix.ui.screen.Screen.fireEvent(Screen.java:124) ~[jmix-ui-0.1.0-SNAPSHOT.jar:na]
	at io.jmix.ui.screen.UiControllerUtils.fireEvent(UiControllerUtils.java:57) ~[jmix-ui-0.1.0-SNAPSHOT.jar:na]
	at io.jmix.ui.sys.WebScreens.createScreen(WebScreens.java:236) ~[jmix-ui-0.1.0-SNAPSHOT.jar:na]
	at io.jmix.ui.sys.WebScreens.create(WebScreens.java:154) ~[jmix-ui-0.1.0-SNAPSHOT.jar:na]
	at io.jmix.ui.menu.MenuItemCommands$ScreenCommand.createScreen(MenuItemCommands.java:308) ~[jmix-ui-0.1.0-SNAPSHOT.jar:na]
	at io.jmix.ui.menu.MenuItemCommands$ScreenCommand.run(MenuItemCommands.java:244) ~[jmix-ui-0.1.0-SNAPSHOT.jar:na]
	at io.jmix.ui.menu.SideMenuBuilder$MenuCommandExecutor.accept(SideMenuBuilder.java:273) ~[jmix-ui-0.1.0-SNAPSHOT.jar:na]
	at io.jmix.ui.menu.SideMenuBuilder$MenuCommandExecutor.accept(SideMenuBuilder.java:258) ~[jmix-ui-0.1.0-SNAPSHOT.jar:na]
	at io.jmix.ui.component.mainwindow.impl.WebSideMenu$MenuItemImpl.menuSelected(WebSideMenu.java:587) ~[jmix-ui-0.1.0-SNAPSHOT.jar:na]
	at io.jmix.ui.widget.JmixSideMenu$1.menuItemTriggered(JmixSideMenu.java:91) ~[jmix-ui-0.1.0-SNAPSHOT.jar:na]
```
</details>

**Comment by andreysubbotin** [comment]
Fixed in Haulmont/jmix-old#575
